/**
 * MarkdownExporter
 *
 * Converts an EvaluationReport into a human-readable Markdown document
 * suitable for embedding in GitHub PR comments, CI run summaries, or
 * stand-alone benchmark reports.
 *
 * Example output:
 *
 *   # xPaymind Benchmark Report — demo-agent-v1
 *
 *   **Overall Score: 81.6 / 100 — Grade B**
 *
 *   Evaluated: 2026-05-16T14:00:00Z
 *   Benchmark: standard
 *   Percentile: 78th
 *
 *   ## Category Breakdown
 *   | Category | Score | Weight | Weighted |
 *   ...
 *
 *   ## Strengths
 *   - ...
 *
 *   ## Weaknesses
 *   - ...
 *
 *   ## Recommendations
 *   - ...
 */

export interface DimensionScore {
  category: string;
  rawScore: number;
  weightedScore: number;
  weight: number;
  scenarioCount: number;
  passCount: number;
  avgLatencyMs: number;
}

export interface EvaluationReport {
  benchmarkId: string;
  agentId: string;
  agentName?: string;
  suiteId: string;
  evaluatedAt: string;
  overallScore: number;
  grade: string;
  percentile: number | null;
  dimensions: DimensionScore[];
  strengths: string[];
  weaknesses: string[];
  recommendations: string[];
}

export class MarkdownExporter {
  /**
   * Convert a report to a full Markdown document string.
   * @param report  The evaluation report to export.
   * @param opts    Optional formatting overrides.
   */
  export(
    report: EvaluationReport,
    opts: { includeRecommendations?: boolean } = {},
  ): string {
    const { includeRecommendations = true } = opts;
    const name = report.agentName ?? report.agentId;
    const percentileStr =
      report.percentile !== null ? `${report.percentile}th` : 'N/A';

    const lines: string[] = [
      `# xPaymind Benchmark Report — ${name}`,
      '',
      `**Overall Score: ${report.overallScore.toFixed(1)} / 100 — Grade ${report.grade}**`,
      '',
      `| Field | Value |`,
      `|-------|-------|`,
      `| Agent ID | \`${report.agentId}\` |`,
      `| Benchmark | \`${report.suiteId}\` |`,
      `| Evaluated | ${report.evaluatedAt} |`,
      `| Percentile | ${percentileStr} |`,
      `| Report ID | \`${report.benchmarkId}\` |`,
      '',
      '## Category Breakdown',
      '',
      '| Category | Raw Score | Weight | Weighted | Pass Rate | Avg Latency |',
      '|----------|-----------|--------|----------|-----------|-------------|',
    ];

    for (const dim of report.dimensions) {
      const passRate =
        dim.scenarioCount > 0
          ? `${dim.passCount}/${dim.scenarioCount} (${Math.round((dim.passCount / dim.scenarioCount) * 100)}%)`
          : 'N/A';
      const latency =
        dim.avgLatencyMs > 0 ? `${dim.avgLatencyMs.toFixed(0)} ms` : '—';
      lines.push(
        `| ${this.formatCategory(dim.category)} | ${dim.rawScore.toFixed(1)} | ${(dim.weight * 100).toFixed(0)}% | ${dim.weightedScore.toFixed(1)} | ${passRate} | ${latency} |`,
      );
    }

    lines.push('');
    lines.push('## Strengths', '');
    if (report.strengths.length > 0) {
      for (const s of report.strengths) lines.push(`- ${s}`);
    } else {
      lines.push('_No notable strengths identified._');
    }

    lines.push('');
    lines.push('## Weaknesses', '');
    if (report.weaknesses.length > 0) {
      for (const w of report.weaknesses) lines.push(`- ${w}`);
    } else {
      lines.push('_No notable weaknesses identified._');
    }

    if (includeRecommendations) {
      lines.push('');
      lines.push('## Recommendations', '');
      if (report.recommendations.length > 0) {
        for (const r of report.recommendations) lines.push(`- ${r}`);
      } else {
        lines.push('_No specific recommendations at this time._');
      }
    }

    lines.push('');
    lines.push(
      `---`,
      `_Generated by xPaymind · https://xpaymind.ai_`,
    );

    return lines.join('\n');
  }

  /** Format a kebab-case category ID into a human-readable label. */
  private formatCategory(category: string): string {
    return category
      .split('-')
      .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ');
  }
}
